repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
    -   id: check-docstring-first
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: pretty-format-json
        args: ["--indent", "2", "--no-sort-keys"]
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
        args: ["-l", "180"]
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ["-m", "3", "--profile", "black", "-l", "180"]
