# Generated by Django 5.1.6 on 2025-04-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatroom",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="chatroom",
            name="private_room",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="name",
            field=models.CharField(max_length=128),
        ),
    ]
